routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/contrato', function () {
    return view('contrato.index');
})->name('contrato');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::resource('envio','EnvioController');
Route::resource('direccion','DireccionController');
Route::resource('usuario','UserController');
Route::resource('envioinforme','EnvioInformeController');
Route::resource('listapaquete','ListaPaqueteController');
Route::resource('comprobante','ComprobanteController');
Route::resource('comprobanteEntrega','ComprobanteEntregaController');
Route::resource('comprobanteFirmado','ComprobanteFirmadoController');
Route::resource('cuentacorriente','CuentaCorrienteController');
Route::post('/cuentacorriente/obtener', 'CuentaCorrienteController@obtener')->name('obtener');

Route::resource('persona','PersonaController');
Route::resource('comercio','ComercioController');
Route::resource('shopping','ShoppingController');
Route::resource('admin','AdminController');
Route::resource('empleado','EmpleadoController');
Route::resource('seguimiento','SeguimientoController');
Route::resource('ajustes','AjustesController');
Route::resource('paquete','PaqueteController');


Route::get('/en-espera', 'EnvioController@showEnEspera')->name('showEnEspera');
Route::get('/en-logistica', 'EnvioController@showEnLogistica')->name('showEnLogistica');
Route::get('/en-transito', 'EnvioController@showEnTransito')->name('showEnTransito');
Route::get('/entregado', 'EnvioController@showEntregado')->name('showEntregado');
Route::post('/envio/comprobanteImpreso', 'EnvioController@comprobanteImpreso')->name('comprobanteImpreso');
Route::get('/shopping/comercios-asociados/{id}', 'ShoppingController@comerciosAsociados')->name('comerciosAsociados');

resources/views/direcciones/create.blade.php
@extends('layouts.innerLayout')

@section('content')


<!-- Sección de registro de envios -->
  
<section id="envios" class="envios">
  <div class="container" data-aos="fade-up">
    
    <div class="section-title mt-5">
      <!-- ======= Alertas ======= -->
      <div class="col-12 col-md-6 offset-md-3">
        @include('alerts.alerts')
      </div>      
      <h2>Registro de Direcciones</h2>
      <p>Por favor ingresa los datos de la dirección de {{$dirOrigenDestino}}</p>
    </div>

    <div class="row">
      <div class="col-12">
        <form method="POST" action="{{ route('direccion.store') }}" role="form" class="php-email-form">
          @csrf   
          
          <div>
            @include('templates.envios.dirOrigenRegister')

          </div>   
          <input type="hidden" id="dirOrigenDestino" name="dirOrigenDestino" value="{{$dirOrigenDestino}}">       
          <div class="row mt-3">
            <div class="col-12 offset-md-4 col-md-4">
              <div class="text-center">
                <button type="submit" class="btn btn-lg btn-success btn-block">Registrar Dirección</button>
              </div>
            </div>
          </div>
          
        </form>

      </div>

    </div>

  </div>
</section>
  
<!-- Fin de sección de registro de envios -->


</main><!-- End #main -->

@endsection

resources/views/direcciones/edit.blade.php
@extends('layouts.innerLayout')

@section('content')


<!-- Sección de registro de envios -->
  
<section id="envios" class="envios">
  <div class="container" data-aos="fade-up">
    
    <div class="section-title mt-5">
      <!-- ======= Alertas ======= -->
      <div class="col-12 col-md-6 offset-md-3">
        @include('alerts.alerts')
      </div>      
      <h2>Registro de envíos</h2>
      <p>Actualización de dirección</p>
    </div>

    <div class="row">
      <div class="col-12">
        {!!Form::open(['route'=>['direccion.update',$direccion->dirId],'method'=>'put'])!!}
          @csrf   
          
          <div>
            @include('templates.envios.dirOrigenUpdate')

          </div>   
          <div class="row mt-3">
            <div class="col-12 offset-md-4 col-md-4">
              <div class="text-center">
                <button type="submit" class="btn btn-lg btn-success btn-block">Actualizar Dirección</button>
              </div>
            </div>
          </div>
          
        {!!Form::close()!!}

      </div>

    </div>

  </div>
</section>
  
<!-- Fin de sección de registro de envios -->


</main><!-- End #main -->

@endsection

resources/views/direcciones/index.blade.php
@extends('layouts.innerLayout')

@section('content')


<!-- Sección de registro de envios -->
  
<section id="envios" class="envios">
  <div class="container" data-aos="fade-up">
    
    <div class="section-title mt-5">
      <!-- ======= Alertas ======= -->
      <div class="col-12 col-md-6 offset-md-3">
        @include('alerts.alerts')
      </div>      
      <h2>Registro de envíos</h2>
      <p>Confirma las direcciones de orígen y destino del envío</p>
    </div>
    <div class="mt-4">
      <p>Seleccione la dirección de orígen del envío o registre una nueva.</p>
    </div>
    <div class="row mt-2">
      @foreach ($direccionesOrigen as $direccion)
        <div class="card">
          <div class="card-body ml-3">
            <input class="form-check-input" type="radio" value="{{$direccion->dirId}}" name="origen">
            <label class="form-check-label" >
              {{$direccion->dirLinea1}}, {{$direccion->dirLinea2}}, {{$direccion->dirCiudad}}, {{$direccion->dirProvincia}}, {{$direccion->dirDepartamento}}, {{$direccion->dirZip}}
            </label>            
            <a href="/direccion/{{$direccion->dirId}}/edit" class="btn btn-secondary btn-sm">Editar esta dirección</a>
          </div>
        </div>
      @endforeach      
    </div>
    <div class="row">
      <div class="col-12">
        <a href="/direccion/create?dirOrigenDestino=origen" class="btn btn-primary btn-sm">Registrar nueva dirección de orígen del envío</a>
      </div>      
    </div>
    @if($direccionesDestino == [])
    <div class="mt-4">
      <p>Para registrar una dirección de destino, use el siguiente botón.</p>      
    </div>
    @else
    <div class="mt-4">
      <p>Seleccione la dirección de destino del envío o registre una nueva.</p>
    </div>
    @endif
    <div class="row mt-2">
      @foreach ($direccionesDestino as $direccion)
        <div class="card">
          <div class="card-body ml-3">
            <input class="form-check-input" type="radio" value="{{$direccion->dirId}}"  name="destino">
            <label class="form-check-label" >
              {{$direccion->dirLinea1}}, {{$direccion->dirLinea2}}, {{$direccion->dirCiudad}}, {{$direccion->dirProvincia}}, {{$direccion->dirDepartamento}}, {{$direccion->dirZip}}
            </label>
            <a href="/direccion/{{$direccion->dirId}}/edit" class="btn btn-secondary btn-sm">Editar esta dirección</a>
          </div>
        </div>
      @endforeach      
    </div>
    <div class="row">
      <div class="col-12">
        <a href="/direccion/create?dirOrigenDestino=destino" class="btn btn-primary btn-sm">Registrar nueva dirección de destino del envío</a>
      </div>      
    </div>
    <div class="row mt-3">
      <div class="col-12 offset-md-4 col-md-4">
        <div class="text-center">
          <!--<button type="submit" class="btn btn-lg btn-success btn-block">Actualizar Dirección</button>-->
          <a onclick="pasarAEnvio()" id="btnSiguiente" href="javascript:void(0);" class="btn btn-lg btn-success btn-block">Siguiente</a>
        </div>
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">


$(document).ready(function() {
  
  $('#btnSiguiente').hide();
  $("input:radio").change(function(){
    var origen = $("input[name='origen']:checked").val();
    var destino = $("input[name='destino']:checked").val();
    var origenChecked = origen?true:false;
    var destinoChecked = destino?true:false;
    console.log("origen:"+origen+", "+"destino:"+destino);
    console.log(origenChecked+", "+destinoChecked);
    if(origenChecked && destinoChecked)
      $('#btnSiguiente').fadeIn('fast');
    else
      $('#btnSiguiente').fadeOut('fast');
  });

});
function pasarAEnvio()
{  
  var origen = $("input[name='origen']:checked").val();
  var destino = $("input[name='destino']:checked").val();
  location.href = '/envio/create?origen='+origen+"&destino="+destino;  
}
  
</script>
<!-- Fin de sección de registro de envios -->


</main><!-- End #main -->

@endsection